name: Deploy Backend to Synology NAS

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup local env
              env:
                BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
                DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
                DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
                DM_EMAIL: ${{ secrets.DM_EMAIL }}
                FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
                GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
                GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                MONGO_URI: ${{secrets.MONGO_URI }}
                NAS_HOST: ${{secrets.NAS_HOST}}
                NAS_SSH_KEY: ${{secrets.NAS_SSH_KEY}}
                NAS_SSH_PORT: ${{secrets.NAS_SSH_PORT}}
                NAS_USERNAME: ${{secrets.NAS_USERNAME}}
                OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
                SESSION_SECRET: ${{secrets.SESSION_SECRET}}
                TAILSCALE_AUTHKEY: ${{secrets.TAILSCALE_AUTHKEY}}
                TAILSCALE_OAUTH_CLIENT_ID: ${{secrets.TAILSCALE_OAUTH_CLIENT_ID}}
                TAILSCALE_OAUTH_SECRET: ${{secrets.TAILSCALE_OAUTH_SECRET}}
                UPLOADS_PATH: ${{secrets.UPLOADS_PATH}}
          
              run: |
                echo ${{secrets.BACKEND_PORT}} | sed 's/./& /g'
                echo ${{secrets.DISCORD_BOT_TOKEN}} | sed 's/./& /g'
                echo ${{secrets.DISCORD_GUILD_ID}} | sed 's/./& /g'
                echo ${{secrets.DM_EMAIL}} | sed 's/./& /g'
                echo ${{secrets.FRONTEND_ORIGIN}} | sed 's/./& /g'
                echo ${{secrets.GOOGLE_CALLBACK_URL}} | sed 's/./& /g'
                echo ${{secrets.GOOGLE_CLIENT_ID}} | sed 's/./& /g'
                echo ${{secrets.GOOGLE_CLIENT_SECRET}} | sed 's/./& /g'
                echo ${{secrets.JWT_SECRET}} | sed 's/./& /g'
                echo ${{secrets.MONGO_URI}} | sed 's/./& /g'
                echo ${{secrets.NAS_HOST}} | sed 's/./& /g'
                echo ${{secrets.NAS_SSH_KEY}} | sed 's/./& /g'
                echo ${{secrets.NAS_SSH_PORT}} | sed 's/./& /g'
                echo ${{secrets.NAS_USERNAME}} | sed 's/./& /g'
                echo ${{secrets.OPENAI_API_KEY}} | sed 's/./& /g'
                echo ${{secrets.SESSION_SECRET}} | sed 's/./& /g'
                echo ${{secrets.TAILSCALE_AUTHKEY}} | sed 's/./& /g'
                echo ${{secrets.TAILSCALE_OAUTH_CLIENT_ID}} | sed 's/./& /g'
                echo ${{secrets.TAILSCALE_OAUTH_SECRET}} | sed 's/./& /g'
                echo ${{secrets.UPLOADS_PATH}} | sed 's/./& /g'

